name: MineShokuTenseiBackpack
version: 1.0
description: MineShoku Tensei backpack plugin by DMan16
main: me.DMan16.BackpackMain
author: DMan16
api-version: 1.21
depend: [MMOProfiles]

commands:
  backpack:
    permission: mst.backpack.use
permissions:
  mst.backpack.extra.*:
    default: false
  mst.backpack.extra:
    default: false
    children:
      mst.backpack.extra.*: true
  mst.backpack.use:
    default: false
  mst.backpack.*:
    default: false
    children:
      mst.backpack.use: true
      mst.backpack.extra: true
  mst.backpack:
    default: op
    children:
      mst.backpack.*: true