name: ${project.name}
version: ${project.version}
description: ${project.description}
main: ${project.groupId}.${project.artifactId}.Main
author: DMan16
api-version: 1.21
depend:
    - MSTUtils

commands:
    backpack:
        permission: mst.backpack.use
permissions:
    mst.backpack.use:
        default: false
    mst.backpack.advanced:
        default: false
        children:
            mst.backpack.use: true
    mst.backpack.*:
        default: false
        children:
            mst.backpack.advanced: true
    mst.backpack:
        default: op
        children:
            mst.backpack.*: true
