name: Build & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual trigger from any branch

permissions:
  contents: write  # required for releases
  actions: write   # required for artifact upload

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for git info plugins like git-commit-id-plugin

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Extract project version from POM
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build with Maven
        run: mvn -B clean package

      - name: Find built JAR
        id: jar
        run: |
          JAR_FILE=$(find target -maxdepth 1 -type f -name "*.jar" | head -n 1)
          echo "jar_file=$JAR_FILE" >> $GITHUB_OUTPUT

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.ref_name }}
          path: ${{ steps.jar.outputs.jar_file }}
          retention-days: 14

  release:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: build-main

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ needs.build.outputs.version }}"
          name: "Release v${{ needs.build.outputs.version }}"
          body: |
            🚀 **Automatic release from main**

            **Version:** v${{ needs.build.outputs.version }}
          files: "*.jar"
